language: ruby
before_script:
  - "rake db:prepare"
rvm:
  - 2.2.2
  - 2.3.1
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails5.gemfile
